# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QBrBg91MtCwt4Q86HV9TbZCbOd3RKGxK

OPTIMASI PREDIKSI KONSUMSI DAYA LISTRIK MENGGUNAKAN METODE REGRESI

1. DATA UNDERSTANDING DAN LOAD DATA
"""

import pandas as pd
import numpy as np

# Cell 1: Load Data dan Data Understanding
# Memuat data apa adanya (tanda '?' tetap dibaca sebagai '?' agar kita tahu kondisinya)
df = pd.read_csv('/content/drive/MyDrive/dataset ml/household_power_consumption.csv', low_memory=False)

# Menampilkan informasi dasar untuk melihat tipe data asli dari file
print("--- Info Dataset ---")
print(df.info())

# Melihat 5 data teratas untuk memahami format penulisan
print("\n--- 5 Data Teratas ---")
display(df.head())

# Melihat statistik deskriptif untuk melihat rentang nilai
print("\n--- Statistik Deskriptif ---")
display(df.describe(include='all'))

# Mengecek keberadaan simbol '?' di dalam dataset
print("\n--- Pengecekan Simbol '?' ---")
print(f"Jumlah baris dengan simbol '?': {(df == '?').sum().sum()}")

"""2. DATA PRE-PROCESSING"""

import pandas as pd
import numpy as np

# 1. Menangani Missing Value
df.replace('?', np.nan, inplace=True)
print("Jumlah missing value sebelum handling:\n", df.isnull().sum())
df.ffill(inplace=True)
print("\nMissing value setelah ffill:", df.isnull().sum().sum())

# 2. Feature Engineering: Mengonversi Date & Time menjadi Datetime Index
df['Datetime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'], dayfirst=True)
df.set_index('Datetime', inplace=True)
df.drop(['Date', 'Time'], axis=1, inplace=True)

# 3. Memastikan semua kolom bertipe float
df = df.astype(float)

# 4. Menambahkan fitur waktu (Sesuai saran sebelumnya yang sudah kita gunakan di EDA)
# Fitur ini bukan "mengarang", tapi mengekstrak informasi dari index Datetime
df['hour'] = df.index.hour

print("\nPreprocessing selesai. Fitur 'hour' telah tersedia.")
display(df.head())

"""3. BOXPLOT"""

import matplotlib.pyplot as plt
import seaborn as sns

# Daftar semua fitur yang kita gunakan
features = ['Global_active_power', 'Global_reactive_power', 'Voltage',
            'Global_intensity', 'Sub_metering_1', 'Sub_metering_2',
            'Sub_metering_3', 'hour']

# Menyiapkan area plot dengan ukuran yang cukup besar
plt.figure(figsize=(16, 12))

# Melakukan perulangan untuk membuat boxplot setiap fitur secara otomatis
for i, col in enumerate(features):
    plt.subplot(3, 3, i + 1) # Membuat layout 3 baris x 3 kolom
    sns.boxplot(y=df[col], color='lightgreen')
    plt.title(f'Boxplot {col}', fontsize=12)
    plt.ylabel('Nilai')
    plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

"""4. EXPLORATORY DATA ANALYSIS (EDA)"""

import matplotlib.pyplot as plt
import seaborn as sns

# Daftar fitur (tanpa target kalau mau dipisah, tapi di sini kita tampilkan semua)
features = df.columns

# 1. Membuat plot distribusi untuk semua fitur
plt.figure(figsize=(16, 12))

for i, col in enumerate(features):
    plt.subplot(3, 3, i + 1)  # sesuaikan dengan jumlah fitur
    sns.histplot(df[col], kde=True)
    plt.title(f'Distribusi {col}')
    plt.xlabel(col)
    plt.ylabel('Frekuensi')
    plt.grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.show()

# 2. Korelasi antar Variabel (Heatmap)
plt.figure(figsize=(10, 8))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Heatmap Korelasi antar Fitur')
plt.show()

"""5. DATA SPLITTING"""

from sklearn.model_selection import train_test_split

# Menentukan Fitur (X) dan Target (y)
# Sesuai rencana regresi kita, target adalah Global_active_power
X = df.drop(['Global_active_power'], axis=1)
y = df['Global_active_power']

# Berdasarkan poin 2 dan 4 petunjuk tugas: Eksperimen 3 kombinasi rasio
ratios = [0.3, 0.2, 0.1] # Representasi 70:30, 80:20, 90:10
split_data = {}

for test_size in ratios:
    train_size_percent = int((1 - test_size) * 100)
    test_size_percent = int(test_size * 100)
    name = f"{train_size_percent}:{test_size_percent}"

    # Splitting tanpa shuffle untuk menjaga urutan waktu (Time Series)
    X_train_temp, X_test_temp, y_train_temp, y_test_temp = train_test_split(
        X, y, test_size=test_size, shuffle=False
    )

    split_data[name] = {
        'X_train': X_train_temp,
        'X_test': X_test_temp,
        'y_train': y_train_temp,
        'y_test': y_test_temp
    }

    print(f"Rasio {name} -> Train: {len(X_train_temp)} | Test: {len(X_test_temp)}")

# Untuk tahap awal pembangunan model, kita gunakan rasio 80:20 sebagai acuan utama
X_train, X_test = split_data["80:20"]['X_train'], split_data["80:20"]['X_test']
y_train, y_test = split_data["80:20"]['y_train'], split_data["80:20"]['y_test']

"""6. Model Building & Hyperparameter Tuning"""

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# --- Tahap Persiapan Fitur & Target (Seluruh Data) ---
X = df.drop(['Global_active_power'], axis=1)
y = df['Global_active_power']

# Feature Scaling tetap dilakukan untuk stabilitas model
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Rasio pembagian sesuai persyaratan tugas
ratios = [(0.3, "70:30"), (0.2, "80:20"), (0.1, "90:10")]

results_list = []

for test_size, label in ratios:
    print(f"\n==== Eksperimen Rasio {label} (Menggunakan Seluruh Data) ====")

    # Splitting data (shuffle=False karena ini data deret waktu/time series)
    X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=test_size, shuffle=False)

    # 1. Linear Regression
    lr = LinearRegression()
    lr.fit(X_train, y_train)

    # 2. Decision Tree + Tuning
    # Menggunakan max_depth agar model tidak overfitting pada data yang besar
    dt = DecisionTreeRegressor(random_state=42)
    dt_param = {'max_depth': [10, 20]}
    dt_grid = GridSearchCV(dt, dt_param, cv=3, n_jobs=-1)
    dt_grid.fit(X_train, y_train)

    # 3. Random Forest + Tuning
    # Catatan: n_estimators dibatasi agar proses training tidak memakan waktu berjam-jam
    rf = RandomForestRegressor(random_state=42)
    rf_param = {'n_estimators': [50], 'max_depth': [10]}
    rf_grid = GridSearchCV(rf, rf_param, cv=2, n_jobs=-1) # cv=2 untuk mempercepat waktu komputasi
    rf_grid.fit(X_train, y_train)

    # List Model untuk Evaluasi
    trained_models = [
        ("Linear Regression", lr),
        ("Decision Tree (Tuned)", dt_grid.best_estimator_),
        ("Random Forest (Tuned)", rf_grid.best_estimator_)
    ]

    # Evaluasi & Penyimpanan Hasil
    for name, model in trained_models:
        y_pred = model.predict(X_test)

        r2 = r2_score(y_test, y_pred)
        mae = mean_absolute_error(y_test, y_pred)
        mse = mean_squared_error(y_test, y_pred)
        rmse = np.sqrt(mse)

        results_list.append({
            'Split_Ratio': label,
            'Algorithm': name,
            'R2_Score': r2,
            'MAE': mae,
            'MSE': mse,
            'RMSE': rmse
        })
        print(f"Selesai: {name} | R2 Score: {r2:.4f}")

print("\nPelatihan pada seluruh data selesai!")

"""7. Model Comparison & Evaluation"""

# 1. Membuat DataFrame dari hasil eksperimen
df_comparison = pd.DataFrame(results_list)

# 2. Menampilkan Tabel Perbandingan Lengkap (MAE, MSE, RMSE, R2)
print("--- Tabel Perbandingan Performa Model (Semua Skenario) ---")
display(df_comparison.sort_values(by=['R2_Score'], ascending=False))
df_comparison = df_comparison.round(4)

# 3. Visualisasi Perbandingan R2 Score antar Rasio Splitting
plt.figure(figsize=(14, 7))
sns.barplot(x='Split_Ratio', y='R2_Score', hue='Algorithm', data=df_comparison)
plt.title('Perbandingan R2 Score: Algoritma vs Rasio Splitting')
plt.ylabel('R2 Score (Akurasi)')
plt.xlabel('Rasio Data Splitting')
plt.ylim(0.8, 1.0) # Fokus pada rentang akurasi tinggi
plt.legend(loc='lower right')
plt.grid(axis='y', alpha=0.3)
plt.show()

# 4. Kesimpulan untuk Laporan
best_row = df_comparison.loc[df_comparison['R2_Score'].idxmax()]
print("\n--- Ringkasan untuk Laporan ---")
print(f"Berdasarkan eksperimen, skenario terbaik adalah menggunakan algoritma {best_row['Algorithm']} "
      f"dengan rasio splitting {best_row['Split_Ratio']}.")
print(f"Hasil R2 Score: {best_row['R2_Score']:.4f}")

"""8. FEATURE IMPORTANT"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Ambil model terbaik
rf_best = rf_grid.best_estimator_

# 2. Ambil nilai feature importance
importances = rf_best.feature_importances_
feature_names = X.columns

# 3. Buat DataFrame & urutkan
feature_importance_df = pd.DataFrame({
    'Feature': feature_names,
    'Importance': importances
}).sort_values(by='Importance', ascending=False)

# 4. Normalisasi ke persen (biar lebih mudah dipahami)
feature_importance_df['Importance (%)'] = feature_importance_df['Importance'] * 100

# 5. Tampilkan Top 10 fitur (lebih fokus & rapi)
top_features = feature_importance_df.head(10)

# 6. Visualisasi
plt.figure(figsize=(10, 6))
sns.barplot(
    x='Importance (%)',
    y='Feature',
    data=top_features
)
plt.title('Top 10 Feature Importance - Random Forest', fontsize=14)
plt.xlabel('Persentase Pengaruh (%)')
plt.ylabel('Fitur')
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# 7. Tabel untuk laporan (dibulatkan biar rapi)
print("\n--- Top 7 Feature Importance ---")
display(top_features.round(4))

"""9. INFERENCE"""

import pickle
import pandas as pd
import numpy as np
import datetime

# 1. Load Model dan Scaler
with open('/content/drive/MyDrive/dataset ml/model_listrik_best.pkl', 'rb') as f:
    model = pickle.load(f)

with open('/content/drive/MyDrive/dataset ml/scaler.pkl', 'rb') as f:
    scaler = pickle.load(f)

# 2. Input Data Mentah (Termasuk Tanggal)
tanggal_input = datetime.date(2006, 12, 17) # Contoh tanggal yang kamu minta
jam_input = 19

data_baru = {
    'Global_reactive_power': [0.1],
    'Voltage': [241.5],
    'Global_intensity': [4.2],
    'Sub_metering_1': [0.0],
    'Sub_metering_2': [1.0],
    'Sub_metering_3': [17.0],
    'hour': [jam_input]
}

# 3. Proses Transformasi dan Prediksi
df_input = pd.DataFrame(data_baru)
# Pastikan urutan kolom sesuai dengan saat scaler di-fit
df_input = df_input[scaler.feature_names_in_] # Menggunakan feature_names_in_ dari scaler untuk menjaga urutan
input_scaled = scaler.transform(df_input)
hasil_prediksi = model.predict(input_scaled)

# 4. Output Lengkap
print(f"--- Hasil Inferensi ---")
print(f"Prediksi Daya (kW): {hasil_prediksi[0]:.4f}")

import pickle

# 1. Simpan Model Random Forest Terbaik
# Pastikan 'rf_grid.best_estimator_' adalah model yang menghasilkan skor 0.999
with open('model_listrik_best.pkl', 'wb') as f:
    pickle.dump(rf_grid.best_estimator_, f)

# 2. Simpan Scaler (WAJIB)
with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

print("Model dan Scaler berhasil disimpan!")